[package]
name = "sbe_md_rust"
version = "0.1.0"
edition = "2021"
authors = ["pedrosfaria2"]

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
sbe_b3__umdf_mbo_sbe = { path = "sbe_b3__umdf_mbo_sbe" }